# Python Blink Counter 

__En__: The goal here is just to look in a face and count how many blinks it counts.  

__PT__: O Objetivo aqui é só olhar em um rosto e contar quantas vezes os olhos piscaram 

In [1]:
import numpy as np 
import cv2

In [2]:
#CascadeClassifiers
eye_cascade = cv2.CascadeClassifier('haarcascade_eye_tree_eyeglasses.xml')
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

first_read = True

#Video Capture
cap = cv2.VideoCapture(0)
ret, img = cap.read()

while(ret):
    ret,img = cap.read()

    gray=cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    #remove impurities
    gray = cv2.bilateralFilter(gray, 5, 1 ,1)

    faces = face_cascade.detectMultiScale(gray, 1.3,5,minSize=(200,200))
    print(faces)
    
    if(len(faces)>0):
        for(x, y, w, h) in faces:
            img = cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 2) 

            #roi_face
            roi_face = gray[y:y+h, x:x+w]
            roi_face_clr = img[y:y+h, x:x+w]
            eyes = eye_cascade.detectMultiScale(roi_face,  1.3,5,minSize=(50,50))

            #Examining 
            if(len(eyes)>1):
                if(first_read):
                    cv2.putText(img, "Eyes detected. Press X to begin", (70,70), cv2.FONT_HERSHEY_PLAIN, 3, (0,255,0),2)
                else:
                    cv2.putText(img, "Eyes open", (70,70), cv2.FONT_HERSHEY_PLAIN, 3, (0,255,0),2)
            else:
                if(first_read):
                    cv2.putText(img, "No eyes detected.", (70,70), cv2.FONT_HERSHEY_PLAIN, 3, (0,255,0),2)
                else:
                    cv2.putText(img, "Eyes open", (70,70), cv2.FONT_HERSHEY_PLAIN, 3, (0,255,0),2)

    else:
         cv2.putText(img, "No face detected.", (170,170), cv2.FONT_HERSHEY_PLAIN, 3, (0,255,0),2)

    cv2.imshow('img', img)
    a = cv2.waitKey(1)
    if(a==ord('q')):
        break
    elif(a==ord('x') and first_read):
        first_read = False

cap.release()
cv2.destroyAllWindows()

[[218 132 255 255]]
[[219 129 255 255]]
[[218 130 255 255]]
[[219 129 255 255]]
[[218 130 255 255]]
[[218 129 255 255]]
[[223 131 255 255]]
[[223 131 255 255]]
[[223 132 255 255]]
[[223 132 255 255]]
[[223 129 255 255]]
[[223 129 255 255]]
[[223 127 255 255]]
[[223 127 255 255]]
[[224 126 255 255]]
[[224 126 255 255]]
()
()
()
()
[[224 126 255 255]]
[[224 126 255 255]]
[[223 127 255 255]]
[[223 127 255 255]]
()
()
[[223 127 255 255]]
[[223 127 255 255]]
()
()
[[226 133 255 255]]
[[226 133 255 255]]
()
()
[[230 136 255 255]]
[[230 136 255 255]]
()
()
[[224 136 255 255]]
[[224 136 255 255]]
()
()
()
()
()
()
()
()
()
()
()
()
()
()
[[223 132 255 255]]
[[223 132 255 255]]
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
[[224 124 255 255]]
[[224 124 255 255]]
[[224 127 255 255]]
[[224 127 255 255]]
()
()
()
()
()
()
[[224 124 255 255]]
[[224 124 255 255]]
[[228 127 255 255]]
[[228 127 255 255]]
()
()
()
()
[[224 127 255 255]]
[[224 127 255 255]]
()
()
()
()
()
()
()
()
[[230 126 255 

[[270 103 263 263]]
[[270 103 263 263]]
[[270 103 263 263]]
[[271 101 264 264]]
[[267 100 264 264]]
[[267 100 264 264]]
[[267 100 264 264]]
[[267 100 264 264]]
[[270 103 263 263]]
[[270 103 263 263]]
[[270 106 264 264]]
[[270 106 264 264]]
[[271 103 263 263]]
[[271 103 263 263]]
[[275 105 255 255]]
[[275 105 255 255]]
[[273 102 263 263]]
[[273 102 263 263]]
[[274 108 255 255]]
[[274 108 255 255]]
[[274 103 263 263]]
[[274 103 263 263]]
[[273 102 263 263]]
[[273 102 263 263]]
[[273 104 263 263]]
[[273 104 263 263]]
[[273 103 261 261]]
[[273 103 261 261]]
[[275 103 262 262]]
[[275 103 262 262]]
[[275 105 261 261]]
[[275 105 261 261]]
[[277 107 255 255]]
[[277 107 255 255]]
[[275 104 263 263]]
[[275 104 263 263]]
[[278 107 255 255]]
[[278 107 255 255]]
[[273 103 261 261]]
[[273 103 261 261]]
[[276 107 263 263]]
[[276 107 263 263]]
[[274 104 262 262]]
[[274 104 262 262]]
[[274 104 263 263]]
[[274 104 263 263]]
[[272 106 262 262]]
[[272 106 262 262]]
[[274 104 262 262]]
[[274 104 262 262]]
