# Python Blink Counter 

__En__: 

__PT__: 

In [1]:
import cv2
import numpy as np

In [2]:
cap = cv2.VideoCapture('videos/people.mp4')
frame_width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
frame_height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

In [3]:
fourcc = cv2.VideoWriter_fourcc('X', 'V', 'I', 'D')

In [4]:
out = cv2.VideoWriter('videos/output.avi', fourcc, 5.0, (1280, 720))

In [5]:
ret, frame1 = cap.read()
ret, frame2 = cap.read()

print(frame1)
print(frame2)

[[[126 126 126]
  [128 128 128]
  [128 128 128]
  ...
  [147 150 148]
  [148 151 149]
  [148 151 149]]

 [[126 126 126]
  [128 128 128]
  [128 128 128]
  ...
  [147 150 148]
  [148 151 149]
  [148 151 149]]

 [[126 126 126]
  [126 126 126]
  [128 128 128]
  ...
  [147 150 148]
  [147 150 148]
  [148 151 149]]

 ...

 [[199 202 200]
  [199 202 200]
  [199 202 200]
  ...
  [229 229 229]
  [229 229 229]
  [229 229 229]]

 [[199 202 200]
  [199 202 200]
  [199 202 200]
  ...
  [229 229 229]
  [229 229 229]
  [229 229 229]]

 [[199 202 200]
  [199 202 200]
  [199 202 200]
  ...
  [229 229 229]
  [229 229 229]
  [229 229 229]]]
[[[126 126 126]
  [128 128 128]
  [128 128 128]
  ...
  [147 150 148]
  [148 151 149]
  [148 151 149]]

 [[126 126 126]
  [128 128 128]
  [128 128 128]
  ...
  [147 150 148]
  [148 151 149]
  [148 151 149]]

 [[126 126 126]
  [126 126 126]
  [128 128 128]
  ...
  [147 150 148]
  [147 150 148]
  [148 151 149]]

 ...

 [[199 202 200]
  [199 202 200]
  [199 202 200]
  ..

In [ ]:
while cap.isOpened():
    diff = cv2.absdiff(frame1, frame2)
    gray = cv2.cvtColor(diff, cv2.COLOR_BGR2GRAY)
    blur = cv2.GaussianBlur(gray, (5,5), 0)
    _, thresh = cv2.threshold(blur, 20, 255, cv2.THRESH_BINARY)
    
    dilated = cv2.dilate(thresh, None, iterations=3)
    contours, _ = cv2.findContours(dilated, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
    
    for contour in contours:
        (x, y, w, h) = cv2.boundingRect(contour)
        
    if cv2.contourArea(contour) < 900:
        continue
    
    cv2.rectangle(frame1, (x, y), (x+w, y+h), (0, 255, 0), 2)
    cv2.putText(frame1, "Status: {}".format('Movement'), (10 , 20), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 3)
    
    image = cv2.resize(frame1, (1280,720))
    out.write(image)
    cv2.imshow("feed", frame1)
    frame1 = frame2
    ret, frame2 = cap.read()
    
    if cv2.waitKey(40) == 27:
        break
    

In [ ]:
cv2.destroyAllWindows()
cap.release()
out.release()